# Leer una tabla html y convertirla a pandas data frame

In [116]:
from bs4 import BeautifulSoup
import urllib.request
URL = 'https://www.todacolombia.com/departamentos-de-colombia/cordoba/municipios-division-politica.html'
pagina = urllib.request.urlopen(URL)
soup = BeautifulSoup(pagina, 'html.parser')
# Buscamos el contenedor de la tabla    
conteneder_tabla = tabla = soup.find('table', {'class': 't-municipios'})
str_tabla = str(conteneder_tabla)
# nos quedamos ocn el "outputHTML" de la tabla
str_tabla = str_tabla[str_tabla.index('<table') : (str_tabla.rindex('</table>') + 8)]
soup = BeautifulSoup(str_tabla, 'html.parser')
tabla = soup.find('table', attrs={'class': 't-municipios'})
dataFrm= pd.read_html(str(tabla))[0]
MunCord=dataFrm.iloc[0:30]
#MunCord.head()
MunCord.tail()
#print(tabla)
#MunCord.to_csv('Municipios.csv')

,CódigoDANE,Municipio,PoblaciónDANE*,ÁreaKm2,Altitudm.s.n.m,Temp.ºC,AñoFundación
25,23686,San Pelayo,44068,470,9,287,1772
26,23417,Santa Cruz de Lorica,119061,1033,7,28,1740
27,23807,Tierralta,102300,4728,51,28,1909
28,23815,Tuchín,38608,110,5,NaN,1826
29,23855,Valencia,43956,892,55,27,1931

In [118]:
MunCord.columns

Index(['CódigoDANE', 'Municipio', 'PoblaciónDANE*', 'ÁreaKm2',
       'Altitudm.s.n.m', 'Temp.ºC', 'AñoFundación'],
      dtype='object')

In [121]:
#pd.set_option('mode.chained_assignment','None')
MunCord.rename(columns={
        'CódigoDANE':'CodDane', 
        'PoblaciónDANE*':'PobDane', 'Temp.ºC':'Temp'})

,CodDane,Municipio,PobDane,ÁreaKm2,Altitudm.s.n.m,Temp,AñoFundación
0,23001,Montería,447716,3043,18,28,1777
1,23068,Ayapel,52156,1929,20,30,1534
2,23079,Buenavista,21915,847,60,35,1950
3,23090,Canalete,22036,394,25,32,1952
4,23162,Cereté,92304,266,15,34,1721
5,23168,Chimá,15165,335,15,33,1777
6,23182,Chinú,48841,624,103,32,1530
7,23189,Ciénaga de Oro,65471,551,13,34,1776
8,23300,Cotorra,15487,89,6,34,1997
9,23350,La Apartada,15482,240,50,27,1957
10,23419,Los Córdobas,24471,430,0,31,1650
11,23464,Momil,14962,152,9,32,1776
12,23466,Montelíbano,83181,1620,44,32,1907
13,23500,Moñitos,27859,206,3,27,1740
14,23555,Planeta Rica,67758,1148,87,29,1885
15,23570,Pueblo Nuevo,39334,819,120,274,1914
16,23574,Puerto Escondido,30019,417,9,277,1854
17,23580,Puerto Libertador,49179,1800,66,29,1941
18,23586,Purísima,15114,122,6,269,1777
19,23660,Sahagún,90093,992,75,27,1675
20,23670,San Andrés de Sotavento,43874,217,117,276,1600
21,23672,San Antero,31942,205,42,273,1647
22,23675,San Bernardo del Viento,35160,318,4,273,1776
23,23678,San Carlos,27486,505,12,28,1777
24,23682,San José de Uré,11172,518,55,NaN,1849
25,23686,San Pelayo,44068,470,9,287,1772
26,23417,Santa Cruz de Lorica,119061,1033,7,28,1740
27,23807,Tierralta,102300,4728,51,28,1909
28,23815,Tuchín,38608,110,5,NaN,1826
29,23855,Valencia,43956,892,55,27,1931

In [122]:
MunCord.columns

Index(['CodDane', 'Municipio', 'PobDane', 'ÁreaKm2', 'Altitudm.s.n.m', 'Temp',
       'AñoFundación'],
      dtype='object')

In [123]:
MunCord.isnull()

    CodDane  Municipio  PobDane  ÁreaKm2  Altitudm.s.n.m   Temp  AñoFundación
0     False      False    False    False           False  False         False
1     False      False    False    False           False  False         False
2     False      False    False    False           False  False         False
3     False      False    False    False           False  False         False
4     False      False    False    False           False  False         False
5     False      False    False    False           False  False         False
6     False      False    False    False           False  False         False
7     False      False    False    False           False  False         False
8     False      False    False    False           False  False         False
9     False      False    False    False           False  False         False
10    False      False    False    False           False  False         False
11    False      False    False    False           False  False         False
12    False      False    False    False           False  False         False
13    False      False    False    False           False  False         False
14    False      False    False    False           False  False         False
15    False      False    False    False           False  False         False
16    False      False    False    False           False  False         False
17    False      False    False    False           False  False         False
18    False      False    False    False           False  False         False
19    False      False    False    False           False  False         False
20    False      False    False    False           False  False         False
21    False      False    False    False           False  False         False
22    False      False    False    False           False  False         False
23    False      False    False    False           False  False         False
24    False      False    False    False           False   True         False
25    False      False    False    False           False  False         False
26    False      False    False    False           False  False         False
27    False      False    False    False           False  False         False
28    False      False    False    False           False   True         False
29    False      False    False    False           False  False         False

In [124]:
# Cuántos datos faltantes hay en cada columna 
MunCord.isnull().sum()

CodDane           0
Municipio         0
PobDane           0
ÁreaKm2           0
Altitudm.s.n.m    0
Temp              2
AñoFundación      0
dtype: int64

In [125]:
MunCord.dropna()

,CodDane,Municipio,PobDane,ÁreaKm2,Altitudm.s.n.m,Temp,AñoFundación
0,23001,Montería,447716,3043,18,28,1777
1,23068,Ayapel,52156,1929,20,30,1534
2,23079,Buenavista,21915,847,60,35,1950
3,23090,Canalete,22036,394,25,32,1952
4,23162,Cereté,92304,266,15,34,1721
5,23168,Chimá,15165,335,15,33,1777
6,23182,Chinú,48841,624,103,32,1530
7,23189,Ciénaga de Oro,65471,551,13,34,1776
8,23300,Cotorra,15487,89,6,34,1997
9,23350,La Apartada,15482,240,50,27,1957
10,23419,Los Córdobas,24471,430,0,31,1650
11,23464,Momil,14962,152,9,32,1776
12,23466,Montelíbano,83181,1620,44,32,1907
13,23500,Moñitos,27859,206,3,27,1740
14,23555,Planeta Rica,67758,1148,87,29,1885
15,23570,Pueblo Nuevo,39334,819,120,274,1914
16,23574,Puerto Escondido,30019,417,9,277,1854
17,23580,Puerto Libertador,49179,1800,66,29,1941
18,23586,Purísima,15114,122,6,269,1777
19,23660,Sahagún,90093,992,75,27,1675
20,23670,San Andrés de Sotavento,43874,217,117,276,1600
21,23672,San Antero,31942,205,42,273,1647
22,23675,San Bernardo del Viento,35160,318,4,273,1776
23,23678,San Carlos,27486,505,12,28,1777
25,23686,San Pelayo,44068,470,9,287,1772
26,23417,Santa Cruz de Lorica,119061,1033,7,28,1740
27,23807,Tierralta,102300,4728,51,28,1909
29,23855,Valencia,43956,892,55,27,1931

In [126]:
MunCord.dropna(axis=1)

,CodDane,Municipio,PobDane,ÁreaKm2,Altitudm.s.n.m,AñoFundación
0,23001,Montería,447716,3043,18,1777
1,23068,Ayapel,52156,1929,20,1534
2,23079,Buenavista,21915,847,60,1950
3,23090,Canalete,22036,394,25,1952
4,23162,Cereté,92304,266,15,1721
5,23168,Chimá,15165,335,15,1777
6,23182,Chinú,48841,624,103,1530
7,23189,Ciénaga de Oro,65471,551,13,1776
8,23300,Cotorra,15487,89,6,1997
9,23350,La Apartada,15482,240,50,1957
10,23419,Los Córdobas,24471,430,0,1650
11,23464,Momil,14962,152,9,1776
12,23466,Montelíbano,83181,1620,44,1907
13,23500,Moñitos,27859,206,3,1740
14,23555,Planeta Rica,67758,1148,87,1885
15,23570,Pueblo Nuevo,39334,819,120,1914
16,23574,Puerto Escondido,30019,417,9,1854
17,23580,Puerto Libertador,49179,1800,66,1941
18,23586,Purísima,15114,122,6,1777
19,23660,Sahagún,90093,992,75,1675
20,23670,San Andrés de Sotavento,43874,217,117,1600
21,23672,San Antero,31942,205,42,1647
22,23675,San Bernardo del Viento,35160,318,4,1776
23,23678,San Carlos,27486,505,12,1777
24,23682,San José de Uré,11172,518,55,1849
25,23686,San Pelayo,44068,470,9,1772
26,23417,Santa Cruz de Lorica,119061,1033,7,1740
27,23807,Tierralta,102300,4728,51,1909
28,23815,Tuchín,38608,110,5,1826
29,23855,Valencia,43956,892,55,1931

In [127]:
MunCord.dropna(axis=0)

,CodDane,Municipio,PobDane,ÁreaKm2,Altitudm.s.n.m,Temp,AñoFundación
0,23001,Montería,447716,3043,18,28,1777
1,23068,Ayapel,52156,1929,20,30,1534
2,23079,Buenavista,21915,847,60,35,1950
3,23090,Canalete,22036,394,25,32,1952
4,23162,Cereté,92304,266,15,34,1721
5,23168,Chimá,15165,335,15,33,1777
6,23182,Chinú,48841,624,103,32,1530
7,23189,Ciénaga de Oro,65471,551,13,34,1776
8,23300,Cotorra,15487,89,6,34,1997
9,23350,La Apartada,15482,240,50,27,1957
10,23419,Los Córdobas,24471,430,0,31,1650
11,23464,Momil,14962,152,9,32,1776
12,23466,Montelíbano,83181,1620,44,32,1907
13,23500,Moñitos,27859,206,3,27,1740
14,23555,Planeta Rica,67758,1148,87,29,1885
15,23570,Pueblo Nuevo,39334,819,120,274,1914
16,23574,Puerto Escondido,30019,417,9,277,1854
17,23580,Puerto Libertador,49179,1800,66,29,1941
18,23586,Purísima,15114,122,6,269,1777
19,23660,Sahagún,90093,992,75,27,1675
20,23670,San Andrés de Sotavento,43874,217,117,276,1600
21,23672,San Antero,31942,205,42,273,1647
22,23675,San Bernardo del Viento,35160,318,4,273,1776
23,23678,San Carlos,27486,505,12,28,1777
25,23686,San Pelayo,44068,470,9,287,1772
26,23417,Santa Cruz de Lorica,119061,1033,7,28,1740
27,23807,Tierralta,102300,4728,51,28,1909
29,23855,Valencia,43956,892,55,27,1931

In [129]:
Temp=MunCord['Temp'].astype('float')
#MunCord.dtypes
#Temp=MunCord['Temp']
#MunCord.astype('Temp' : 'float')
MunCord.head()
#Temp=MunCord.Temp

  CodDane   Municipio PobDane ÁreaKm2 Altitudm.s.n.m Temp AñoFundación
0   23001    Montería  447716    3043             18   28         1777
1   23068      Ayapel   52156    1929             20   30         1534
2   23079  Buenavista   21915     847             60   35         1950
3   23090    Canalete   22036     394             25   32         1952
4   23162      Cereté   92304     266             15   34         1721

In [130]:
Temp.head()

0    28.0
1    30.0
2    35.0
3    32.0
4    34.0
Name: Temp, dtype: float64

In [131]:
Temp.tail()

25    287.0
26     28.0
27     28.0
28      NaN
29     27.0
Name: Temp, dtype: float64

In [133]:
Temp[Temp>100]=Temp/10
Temp.head()

0    28.0
1    30.0
2    35.0
3    32.0
4    34.0
Name: Temp, dtype: float64

In [134]:
TempMed=Temp.dropna().mean()
TempMed

29.639285714285712

In [135]:
Temp.fillna(TempMed,inplace=True)
Temp.tail()

25    28.700000
26    28.000000
27    28.000000
28    29.639286
29    27.000000
Name: Temp, dtype: float64